로그인 페이지 개발
Seoulog/FE pull request #10
Opened 2023-11-18 12:23 UTC by Minggurazi

https://www.notion.so/seoul-log/8-ce8d9ec9a1e44c4eb64d9dbc6b4c4ed0?pvs=4

2023-11-18 12:42 UTC, PMtHk requested changes
form 부분은 component/form에 위치하는건 어떨까요?
validation 부분은 lib/validation에 위치시키고,
login 함수 도 분리하면, 최대한 컴포넌트를 하나의 기능에 충실하게 만들 수 있을 것 같아요.

2023-11-18 14:13 UTC, Minggurazi commented
> form 부분은 component/form에 위치하는건 어떨까요? validation 부분은 lib/validation에 위치시키고, login 함수 도 분리하면, 최대한 컴포넌트를 하나의 기능에 충실하게 만들 수 있을 것 같아요.

component 폴더에는 재사용 가능한 컴포넌트가 위치하는게 맞다고 생각하는데 login에 사용되는 form은 재사용될 가능성이 없어보여서 현재 위치가 적당한것 같습니다. validate 함수 마찬가지라고 생각합니다.
login 함수는 따로 분리하도록 하겠습니다!

2023-11-25 17:49 UTC, songsurl00 approved these changes

2023-11-29 10:41 UTC, PMtHk approved these changes

2023-11-29 10:42 UTC, merged